"""Curated headquarters/campus locations for high-volume IIDS applicants (manual tier)."""
from __future__ import annotations

# applicant_name -> (city, province, source_url, geo_match_confidence, notes)
# Only high-confidence CN HQ/campus; foreign parents excluded at apply time.

CURATED_LOCATIONS: dict[str, tuple[str, str, str, str, str]] = {
    # Phase A (also in apply_priority1 script)
    "HUAWEI TECH CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.huawei.com/en/corporate-information",
        "official_headquarters_page",
        "Official corporate information.",
    ),
    "BOE TECHNOLOGY GROUP CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.boe.com/en/about-boe",
        "official_headquarters_page",
        "Official company profile.",
    ),
    "ALIBABA GROUP HOLDING LTD": (
        "Hangzhou",
        "Zhejiang",
        "https://www.alibabagroup.com/en-US/contact",
        "official_headquarters_page",
        "Official group contact.",
    ),
    "UNIV ZHEJIANG": (
        "Hangzhou",
        "Zhejiang",
        "https://www.zju.edu.cn/english/",
        "university_location",
        "Zhejiang University.",
    ),
    "STATE GRID CORP CHINA": (
        "Beijing",
        "Beijing",
        "https://www.sgcc.com.cn/html/sgcc_en/",
        "official_headquarters_page",
        "State Grid Corporation.",
    ),
    "UNIV TSINGHUA": (
        "Beijing",
        "Beijing",
        "https://www.tsinghua.edu.cn/en/",
        "university_location",
        "Tsinghua University.",
    ),
    "UNIV SOUTH CHINA TECH": (
        "Guangzhou",
        "Guangdong",
        "https://www.scut.edu.cn/en/",
        "university_location",
        "South China University of Technology.",
    ),
    "UNIV SOUTHEAST": (
        "Nanjing",
        "Jiangsu",
        "https://www.seu.edu.cn/english/",
        "university_location",
        "Southeast University.",
    ),
    "ZTE CORP": (
        "Shenzhen",
        "Guangdong",
        "https://www.zte.com.cn/global/about/corporate_information.html",
        "official_headquarters_page",
        "ZTE Corporation.",
    ),
    "UNIV ELECTRONIC SCI & TECH CHINA": (
        "Chengdu",
        "Sichuan",
        "https://www.uestc.edu.cn/en/",
        "university_location",
        "UESTC.",
    ),
    "UNIV XIDIAN": (
        "Xi'an",
        "Shaanxi",
        "https://en.xidian.edu.cn/",
        "university_location",
        "Xidian University.",
    ),
    "UNIV HUAZHONG SCIENCE TECH": (
        "Wuhan",
        "Hubei",
        "https://english.hust.edu.cn/",
        "university_location",
        "Huazhong University of Science and Technology.",
    ),
    "UNIV SHANDONG": (
        "Jinan",
        "Shandong",
        "https://www.sdu.edu.cn/english/",
        "university_location",
        "Shandong University.",
    ),
    "UNIV BEIHANG": (
        "Beijing",
        "Beijing",
        "https://ev.buaa.edu.cn/",
        "university_location",
        "Beihang University.",
    ),
    "UNIV GUANGDONG TECHNOLOGY": (
        "Guangzhou",
        "Guangdong",
        "https://www.gdut.edu.cn/",
        "university_location",
        "Guangdong University of Technology.",
    ),
    "UNIV CENTRAL SOUTH": (
        "Changsha",
        "Hunan",
        "https://www.csu.edu.cn/",
        "university_location",
        "Central South University.",
    ),
    "UNIV ZHEJIANG TECHNOLOGY": (
        "Hangzhou",
        "Zhejiang",
        "https://www.zjut.edu.cn/",
        "university_location",
        "Zhejiang University of Technology.",
    ),
    "UNIV JILIN": (
        "Changchun",
        "Jilin",
        "https://www.jlu.edu.cn/",
        "university_location",
        "Jilin University.",
    ),
    "CHINA PETROLEUM & CHEM CORP": (
        "Beijing",
        "Beijing",
        "https://www.sinopecgroup.com/group/en/",
        "official_headquarters_page",
        "Sinopec Group.",
    ),
    "GUANGDONG POWER GRID CO": (
        "Guangzhou",
        "Guangdong",
        "https://www.gd.csg.cn/",
        "official_headquarters_page",
        "China Southern Power Grid Guangdong.",
    ),
    "UNIV SICHUAN": (
        "Chengdu",
        "Sichuan",
        "https://en.scu.edu.cn/",
        "university_location",
        "Sichuan University.",
    ),
    "UNIV HOHAI": (
        "Nanjing",
        "Jiangsu",
        "https://www.hhu.edu.cn/",
        "university_location",
        "Hohai University.",
    ),
    "CHINA UNICOM": (
        "Beijing",
        "Beijing",
        "https://www.chinaunicom.com.cn/",
        "official_headquarters_page",
        "China Unicom.",
    ),
    "UNIV TONGJI": (
        "Shanghai",
        "Shanghai",
        "https://www.tongji.edu.cn/",
        "university_location",
        "Tongji University.",
    ),
    "UNIV NORTHWESTERN POLYTECHNICAL": (
        "Xi'an",
        "Shaanxi",
        "https://en.nwpu.edu.cn/",
        "university_location",
        "Northwestern Polytechnical University.",
    ),
    "UNIV JIANGSU": (
        "Zhenjiang",
        "Jiangsu",
        "https://en.ujs.edu.cn/",
        "university_location",
        "Jiangsu University.",
    ),
    "UNIV JIANGNAN": (
        "Wuxi",
        "Jiangsu",
        "https://en.jiangnan.edu.cn/",
        "university_location",
        "Jiangnan University.",
    ),
    "UNIV SUN YAT SEN": (
        "Guangzhou",
        "Guangdong",
        "https://www.sysu.edu.cn/",
        "university_location",
        "Sun Yat-sen University.",
    ),
    "PETROCHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.petrochina.com.cn/ptr/",
        "official_headquarters_page",
        "PetroChina.",
    ),
    "VIVO COMM TECHNOLOGY CO LTD": (
        "Dongguan",
        "Guangdong",
        "https://www.vivo.com/en/about-vivo",
        "official_headquarters_page",
        "vivo.",
    ),
    "UNIV BEIJING POSTS & TELECOMM": (
        "Beijing",
        "Beijing",
        "https://www.bupt.edu.cn/",
        "university_location",
        "Beijing University of Posts and Telecommunications.",
    ),
    "GUANGDONG MIDEA DOMESTIC ELECTRICAL APPLIANCE MFG CO LTD": (
        "Foshan",
        "Guangdong",
        "https://www.midea.com/en/about-midea",
        "official_headquarters_page",
        "Midea Group.",
    ),
    "YANGTZE MEMORY TECH CO LTD": (
        "Wuhan",
        "Hubei",
        "https://www.ymtc.com/en/",
        "official_headquarters_page",
        "YMTC.",
    ),
    "NINGDE CONTEMPORARY AMPEREX TECH CO LTD": (
        "Ningde",
        "Fujian",
        "https://www.catl.com/en/",
        "official_headquarters_page",
        "CATL.",
    ),
    "UNIV SOUTHWEST JIAOTONG": (
        "Chengdu",
        "Sichuan",
        "https://en.swjtu.edu.cn/",
        "university_location",
        "Southwest Jiaotong University.",
    ),
    "UNIV NORTHEASTERN": (
        "Shenyang",
        "Liaoning",
        "https://www.neu.edu.cn/",
        "university_location",
        "Northeastern University (China).",
    ),
    "BYD CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.byd.com/en/",
        "official_headquarters_page",
        "BYD.",
    ),
    "NAT UNIV DEFENSE TECHNOLOGY PLA": (
        "Changsha",
        "Hunan",
        "https://www.nudt.edu.cn/",
        "university_location",
        "National University of Defense Technology.",
    ),
    "BANK OF CHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.boc.cn/",
        "official_headquarters_page",
        "Bank of China.",
    ),
    "UNIV BEIJING": (
        "Beijing",
        "Beijing",
        "https://english.pku.edu.cn/",
        "university_location",
        "Peking University.",
    ),
    "UNIV FUDAN": (
        "Shanghai",
        "Shanghai",
        "https://www.fudan.edu.cn/en/",
        "university_location",
        "Fudan University.",
    ),
    "CHINA ELECTRIC POWER RES INST CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.epri.sgcc.com.cn/",
        "official_headquarters_page",
        "China Electric Power Research Institute.",
    ),
    "INDUSTRIAL & COMMERCIAL BANK OF CHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.icbc.com.cn/icbc/",
        "official_headquarters_page",
        "ICBC.",
    ),
    # Phase C — high incremental (no city token in applicant name)
    "UNIV TIANJIN": (
        "Tianjin",
        "Tianjin",
        "https://www.tju.edu.cn/en/",
        "university_location",
        "Tianjin University.",
    ),
    "GUANGDONG OPPO MOBILE TELECOMMUNICATIONS CORP LTD": (
        "Dongguan",
        "Guangdong",
        "https://www.oppo.com/en/about/",
        "official_headquarters_page",
        "OPPO Guangdong Mobile Telecommunications.",
    ),
    "OPPO GUANGDONG MOBILE TELECOMMUNICATIONS CO LTD": (
        "Dongguan",
        "Guangdong",
        "https://www.oppo.com/en/about/",
        "official_headquarters_page",
        "OPPO Guangdong Mobile Telecommunications.",
    ),
    "UNIV SOUTHWEST PETROLEUM": (
        "Chengdu",
        "Sichuan",
        "https://www.swpu.edu.cn/",
        "university_location",
        "Southwest Petroleum University.",
    ),
    "UNIV CHINA MINING": (
        "Xuzhou",
        "Jiangsu",
        "https://www.cumt.edu.cn/",
        "university_location",
        "China University of Mining and Technology.",
    ),
    "UNIV CHINA THREE GORGES CTGU": (
        "Yichang",
        "Hubei",
        "https://www.ctgu.edu.cn/",
        "university_location",
        "China Three Gorges University.",
    ),
    "UNIV JILIANG CHINA": (
        "Hangzhou",
        "Zhejiang",
        "https://www.cjlu.edu.cn/",
        "university_location",
        "China Jiliang University.",
    ),
    "UNIV SCIENCE & TECHNOLOGY CHINA": (
        "Hefei",
        "Anhui",
        "https://www.ustc.edu.cn/",
        "university_location",
        "University of Science and Technology of China.",
    ),
    "UNIV SHANDONG SCIENCE & TECH": (
        "Qingdao",
        "Shandong",
        "https://www.sdust.edu.cn/",
        "university_location",
        "Shandong University of Science and Technology.",
    ),
    "NUBIA TECHNOLOGY CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.nubia.com/",
        "official_headquarters_page",
        "Nubia Technology.",
    ),
    "UNIV HUNAN": (
        "Changsha",
        "Hunan",
        "https://www.hnu.edu.cn/",
        "university_location",
        "Hunan University.",
    ),
    "ZHEJIANG DAHUA TECHNOLOGY CO": (
        "Hangzhou",
        "Zhejiang",
        "https://www.dahuatech.com/",
        "official_headquarters_page",
        "Zhejiang Dahua Technology.",
    ),
    "UNIV SHAANXI SCIENCE & TECH": (
        "Xi'an",
        "Shaanxi",
        "https://www.sust.edu.cn/",
        "university_location",
        "Shaanxi University of Science and Technology.",
    ),
    "UNIV NORTH CHINA ELECTRIC POWER": (
        "Beijing",
        "Beijing",
        "https://www.ncepu.edu.cn/",
        "university_location",
        "North China Electric Power University.",
    ),
    "CHANGAN UNIV": (
        "Xi'an",
        "Shaanxi",
        "https://www.chd.edu.cn/",
        "university_location",
        "Chang'an University.",
    ),
    "CHINA CONSTRUCTION BANK CORP": (
        "Beijing",
        "Beijing",
        "https://www.ccb.com/",
        "official_headquarters_page",
        "China Construction Bank.",
    ),
    "UNIV GUILIN ELECTRONIC TECH": (
        "Guilin",
        "Guangxi",
        "https://www.guet.edu.cn/",
        "university_location",
        "Guilin University of Electronic Technology.",
    ),
    "UNIV CHINA AGRICULTURAL": (
        "Beijing",
        "Beijing",
        "https://www.cau.edu.cn/",
        "university_location",
        "China Agricultural University.",
    ),
    "SVOLT ENERGY TECH CO LTD": (
        "Changzhou",
        "Jiangsu",
        "https://www.svolt.cn/",
        "official_headquarters_page",
        "Svolt Energy Technology.",
    ),
    "H3C HOLDING LTD": (
        "Hangzhou",
        "Zhejiang",
        "https://www.h3c.com/en/",
        "official_headquarters_page",
        "H3C Technologies.",
    ),
    "CHANGXIN MEMORY TECH INC": (
        "Hefei",
        "Anhui",
        "https://www.cxmt.com/",
        "official_headquarters_page",
        "ChangXin Memory Technologies (CXMT).",
    ),
    "UNIV SOUTH CHINA NORMAL": (
        "Guangzhou",
        "Guangdong",
        "https://www.scnu.edu.cn/",
        "university_location",
        "South China Normal University.",
    ),
    "UNIV HEBEI TECHNOLOGY": (
        "Tianjin",
        "Tianjin",
        "https://www.hebut.edu.cn/",
        "university_location",
        "Hebei University of Technology.",
    ),
    "CHINA TELECOM CORP LTD": (
        "Beijing",
        "Beijing",
        "https://www.chinatelecom.com.cn/",
        "official_headquarters_page",
        "China Telecom.",
    ),
    "UNIV GUANGXI": (
        "Nanning",
        "Guangxi",
        "https://www.gxu.edu.cn/",
        "university_location",
        "Guangxi University.",
    ),
    "KUNSHAN GOVISIONOX OPTOELECTRONICS CO LTD": (
        "Kunshan",
        "Jiangsu",
        "https://www.govisionox.com/",
        "official_headquarters_page",
        "Kunshan Govisionox Optoelectronics.",
    ),
    "INST MICROELECTRONICS CAS": (
        "Beijing",
        "Beijing",
        "https://english.ime.cas.cn/",
        "university_location",
        "Institute of Microelectronics, CAS.",
    ),
    "UNIV CHINA PETROLEUM EAST CHINA": (
        "Qingdao",
        "Shandong",
        "https://www.upc.edu.cn/",
        "university_location",
        "China University of Petroleum (East China).",
    ),
    "UNIV ANHUI SCI & TECHNOLOGY": (
        "Hefei",
        "Anhui",
        "https://www.ahstu.edu.cn/",
        "university_location",
        "Anhui Science and Technology University.",
    ),
    "ELECTRIC POWER RES INST CO LTD CSG": (
        "Guangzhou",
        "Guangdong",
        "https://www.epri.csg.cn/",
        "official_headquarters_page",
        "Electric Power Research Institute, CSG.",
    ),
    "SZ DJI TECHNOLOGY CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.dji.com/company",
        "official_headquarters_page",
        "DJI.",
    ),
    "SICHUAN CHANGHONG ELECTRIC CO LTD": (
        "Mianyang",
        "Sichuan",
        "https://www.changhong.com/",
        "official_headquarters_page",
        "Sichuan Changhong Electric.",
    ),
    "DALIAN INST CHEM & PHYSICS CAS": (
        "Dalian",
        "Liaoning",
        "https://english.dicp.cas.cn/",
        "university_location",
        "Dalian Institute of Chemical Physics, CAS.",
    ),
    "UNIV BEIJING SCIENCE & TECH": (
        "Beijing",
        "Beijing",
        "https://www.ustb.edu.cn/",
        "university_location",
        "University of Science and Technology Beijing.",
    ),
    "BEIJING BYTEDANCE NETWORK TECH CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.bytedance.com/en/",
        "official_headquarters_page",
        "ByteDance.",
    ),
    "CHINA MOBILE COMMUNICATIONS GROUP CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.chinamobileltd.com/en/",
        "official_headquarters_page",
        "China Mobile.",
    ),
    "AGRICULTURAL BANK OF CHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.abchina.com/en/",
        "official_headquarters_page",
        "Agricultural Bank of China.",
    ),
    "CHINA MERCHANTS BANK CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.cmbchina.com/",
        "official_headquarters_page",
        "China Merchants Bank.",
    ),
    "PING AN INSURANCE GROUP CO OF CHINA LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.pingan.cn/",
        "official_headquarters_page",
        "Ping An Insurance.",
    ),
    "CHINA CITIC BANK CORP LTD": (
        "Beijing",
        "Beijing",
        "https://www.citicbank.com/",
        "official_headquarters_page",
        "China CITIC Bank.",
    ),
    "UNIV NANJING AERONAUTICS & ASTRONAUTICS": (
        "Nanjing",
        "Jiangsu",
        "https://www.nuaa.edu.cn/",
        "university_location",
        "Nanjing University of Aeronautics and Astronautics.",
    ),
    "UNIV DALIAN TECH": (
        "Dalian",
        "Liaoning",
        "https://www.dlut.edu.cn/",
        "university_location",
        "Dalian University of Technology.",
    ),
    "UNIV HEFEI TECHNOLOGY": (
        "Hefei",
        "Anhui",
        "https://www.hfut.edu.cn/",
        "university_location",
        "Hefei University of Technology.",
    ),
    "UNIV KUNMING SCIENCE & TECH": (
        "Kunming",
        "Yunnan",
        "https://www.kmust.edu.cn/",
        "university_location",
        "Kunming University of Science and Technology.",
    ),
    "UNIV HARBIN ENG": (
        "Harbin",
        "Heilongjiang",
        "https://www.hrbeu.edu.cn/",
        "university_location",
        "Harbin Engineering University.",
    ),
    "UNIV HARBIN SCIENCE & TECH": (
        "Harbin",
        "Heilongjiang",
        "https://www.hrbust.edu.cn/",
        "university_location",
        "Harbin University of Science and Technology.",
    ),
    "UNIV CHONGQING POSTS & TELECOM": (
        "Chongqing",
        "Chongqing",
        "https://www.cqupt.edu.cn/",
        "university_location",
        "Chongqing University of Posts and Telecommunications.",
    ),
    "WUHAN CHINA STAR OPTOELECTRONICS SEMICONDUCTOR DISPLAY TECH CO LTD": (
        "Wuhan",
        "Hubei",
        "https://www.tclcsot.com/",
        "official_headquarters_page",
        "China Star Optoelectronics (TCL CSOT).",
    ),
    "ZHENGZHOU YUNHAI INFORMATION TECH CO LTD": (
        "Zhengzhou",
        "Henan",
        "https://www.yunhai.cn/",
        "official_headquarters_page",
        "Zhengzhou Yunhai Information Technology.",
    ),
    "SHENZHEN POWER SUPPLY BUREAU": (
        "Shenzhen",
        "Guangdong",
        "https://www.sz.csg.cn/",
        "official_headquarters_page",
        "Shenzhen Power Supply Bureau, CSG.",
    ),
    "CHINA SOUTHERN POWER GRID CO LTD": (
        "Guangzhou",
        "Guangdong",
        "https://www.csg.cn/",
        "official_headquarters_page",
        "China Southern Power Grid.",
    ),
    "STATE GRID SHANGHAI MUNICIPAL ELECTRIC POWER CO": (
        "Shanghai",
        "Shanghai",
        "https://www.sh.sgcc.com.cn/",
        "official_headquarters_page",
        "State Grid Shanghai.",
    ),
    "CHINA STATE CONSTRUCTION ENGR CORP LTD": (
        "Beijing",
        "Beijing",
        "https://www.cscec.com/",
        "official_headquarters_page",
        "China State Construction Engineering.",
    ),
    "CHINA RAILWAY CONSTRUCTION CORP LTD": (
        "Beijing",
        "Beijing",
        "https://www.crcc.cn/",
        "official_headquarters_page",
        "China Railway Construction.",
    ),
    "CHINA COMMUNICATIONS CONSTRUCTION CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.ccccltd.cn/",
        "official_headquarters_page",
        "China Communications Construction.",
    ),
    "CHINA RAILWAY GROUP LTD": (
        "Beijing",
        "Beijing",
        "https://www.crec.cn/",
        "official_headquarters_page",
        "China Railway Group.",
    ),
    "CHINA LIFE INSURANCE CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.chinalife.com.cn/",
        "official_headquarters_page",
        "China Life Insurance.",
    ),
    "POSTAL SAVINGS BANK OF CHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.psbc.com/en/",
        "official_headquarters_page",
        "Postal Savings Bank of China.",
    ),
    "CHINA PACIFIC INSURANCE GROUP CO LTD": (
        "Shanghai",
        "Shanghai",
        "https://www.cpic.com.cn/",
        "official_headquarters_page",
        "China Pacific Insurance.",
    ),
    "CHINA SHIPBUILDING INDUSTRY CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.csicl.com.cn/",
        "official_headquarters_page",
        "China Shipbuilding Industry.",
    ),
    "CHINA NATIONAL OFFSHORE OIL CORP": (
        "Beijing",
        "Beijing",
        "https://www.cnooc.com.cn/",
        "official_headquarters_page",
        "CNOOC Group.",
    ),
    "CHINA NATIONAL PETROLEUM CORP": (
        "Beijing",
        "Beijing",
        "https://www.cnpc.com.cn/",
        "official_headquarters_page",
        "CNPC.",
    ),
    "CHINA AEROSPACE SCIENCE & TECHNOLOGY CORP": (
        "Beijing",
        "Beijing",
        "https://www.spacechina.com/",
        "official_headquarters_page",
        "China Aerospace Science and Technology Corporation.",
    ),
    "CHINA AEROSPACE SCIENCE & INDUSTRY CORP": (
        "Beijing",
        "Beijing",
        "https://www.casic.com.cn/",
        "official_headquarters_page",
        "China Aerospace Science and Industry Corporation.",
    ),
    # Phase D — top-2000 CN applicants without city tokens in English IIDS names
    "UNIV TIANJIN": (
        "Tianjin",
        "Tianjin",
        "https://www.tju.edu.cn/english/",
        "university_location",
        "Tianjin University.",
    ),
    "YUNNAN POWER GRID CO LTD ELECTRIC POWER RES INST": (
        "Kunming",
        "Yunnan",
        "https://www.yn.csg.cn/",
        "official_headquarters_page",
        "Yunnan Power Grid / EPRI.",
    ),
    "UNIV GUIZHOU": (
        "Guiyang",
        "Guizhou",
        "https://www.gzu.edu.cn/",
        "university_location",
        "Guizhou University.",
    ),
    "NINGDE AMPEREX TECHNOLOGY LTD": (
        "Ningde",
        "Fujian",
        "https://www.catl.com/",
        "official_headquarters_page",
        "CATL (Amperex Technology).",
    ),
    "UNIV ZHEJIANG SCIENCE & TECH": (
        "Hangzhou",
        "Zhejiang",
        "https://www.zust.edu.cn/",
        "university_location",
        "Zhejiang University of Science and Technology.",
    ),
    "RES INST CHINA MOBILE COMMUNICATIONS CORP": (
        "Beijing",
        "Beijing",
        "https://www.chinamobileltd.com/en/",
        "official_headquarters_page",
        "China Mobile Research Institute.",
    ),
    "UNIV ANHUI": (
        "Hefei",
        "Anhui",
        "https://www.ahu.edu.cn/",
        "university_location",
        "Anhui University.",
    ),
    "INST AUTOMATION CAS": (
        "Beijing",
        "Beijing",
        "https://english.ia.cas.cn/",
        "university_location",
        "Institute of Automation, CAS.",
    ),
    "CHINA ELECTRIC POWER RES INST": (
        "Beijing",
        "Beijing",
        "https://www.epri.sgcc.com.cn/",
        "official_headquarters_page",
        "China Electric Power Research Institute.",
    ),
    "UNIV HENAN POLYTECHNIC": (
        "Jiaozuo",
        "Henan",
        "https://www.hpu.edu.cn/",
        "university_location",
        "Henan Polytechnic University.",
    ),
    "UNIV SOUTH CHINA AGRICULT": (
        "Guangzhou",
        "Guangdong",
        "https://www.scau.edu.cn/",
        "university_location",
        "South China Agricultural University.",
    ),
    "FIBERHOME TELECOMMUNICATION TECH CO LTD": (
        "Wuhan",
        "Hubei",
        "https://www.fiberhome.com/",
        "official_headquarters_page",
        "FiberHome Technologies.",
    ),
    "UNIV JIANGSU SCIENCE & TECH": (
        "Zhenjiang",
        "Jiangsu",
        "https://www.ujs.edu.cn/",
        "university_location",
        "Jiangsu University of Science and Technology.",
    ),
    "UNIV EAST CHINA NORMAL": (
        "Shanghai",
        "Shanghai",
        "https://english.ecnu.edu.cn/",
        "university_location",
        "East China Normal University.",
    ),
    "GUIZHOU POWER GRID CO LTD": (
        "Guiyang",
        "Guizhou",
        "https://www.gz.csg.cn/",
        "official_headquarters_page",
        "Guizhou Power Grid.",
    ),
    "UNIV SHANXI": (
        "Taiyuan",
        "Shanxi",
        "https://www.sxu.edu.cn/",
        "university_location",
        "Shanxi University.",
    ),
    "ELECTRIC POWER RES INST GUANGDONG POWER GRID CORP": (
        "Guangzhou",
        "Guangdong",
        "https://www.gd.csg.cn/",
        "official_headquarters_page",
        "Guangdong Power Grid EPRI.",
    ),
    "TAIKANG INSURANCE GROUP CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.taikang.com/",
        "official_headquarters_page",
        "Taikang Insurance Group.",
    ),
    "UNIV HUAQIAO": (
        "Quanzhou",
        "Fujian",
        "https://www.hqu.edu.cn/",
        "university_location",
        "Huaqiao University.",
    ),
    "UNIV NANKAI": (
        "Tianjin",
        "Tianjin",
        "https://en.nankai.edu.cn/",
        "university_location",
        "Nankai University.",
    ),
    "UNIV HUBEI TECHNOLOGY": (
        "Wuhan",
        "Hubei",
        "https://www.hbut.edu.cn/",
        "university_location",
        "Hubei University of Technology.",
    ),
    "OCEAN UNIV CHINA": (
        "Qingdao",
        "Shandong",
        "https://www.ouc.edu.cn/",
        "university_location",
        "Ocean University of China.",
    ),
    "VIVO MOBILE COMMUNICATION CO LTD": (
        "Dongguan",
        "Guangdong",
        "https://www.vivo.com/",
        "official_headquarters_page",
        "vivo Mobile Communication.",
    ),
    "UNIV EAST CHINA SCIENCE & TECH": (
        "Shanghai",
        "Shanghai",
        "https://www.ecust.edu.cn/",
        "university_location",
        "East China University of Science and Technology.",
    ),
    "CHINA INST WATER RESOURCES & HYDROPOWER RES": (
        "Beijing",
        "Beijing",
        "https://www.iwhr.com/",
        "official_headquarters_page",
        "China Institute of Water Resources and Hydropower Research.",
    ),
    "UNIV FUJIAN": (
        "Fuzhou",
        "Fujian",
        "https://www.fzu.edu.cn/",
        "university_location",
        "Fujian University.",
    ),
    "DATANG MOBILE COMMUNICATIONS EQUIPMENT CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.datangmobile.cn/",
        "official_headquarters_page",
        "Datang Mobile Communications Equipment.",
    ),
    "UNIV SOOCHOW": (
        "Suzhou",
        "Jiangsu",
        "https://www.suda.edu.cn/",
        "university_location",
        "Soochow University.",
    ),
    "UBTECH ROBOTICS CORP": (
        "Shenzhen",
        "Guangdong",
        "https://www.ubtrobot.com/",
        "official_headquarters_page",
        "UBTECH Robotics.",
    ),
    "PING AN LIFE INSURANCE CO CHINA LTD": (
        "Shenzhen",
        "Guangdong",
        "https://life.pingan.com/",
        "official_headquarters_page",
        "Ping An Life Insurance.",
    ),
    "UNIV NORTH CHINA": (
        "Taiyuan",
        "Shanxi",
        "https://www.ncu.edu.cn/",
        "university_location",
        "North University of China.",
    ),
    "UNIV QILU TECHNOLOGY": (
        "Jinan",
        "Shandong",
        "https://www.qlu.edu.cn/",
        "university_location",
        "Qilu University of Technology.",
    ),
    "ELECTRIC POWER RES INST OF STATE GRID SHANDONG ELECTRIC POWER CO": (
        "Jinan",
        "Shandong",
        "https://www.sd.sgcc.com.cn/",
        "official_headquarters_page",
        "State Grid Shandong EPRI.",
    ),
    "UNIV NORTHWEST A&F": (
        "Yangling",
        "Shaanxi",
        "https://www.nwafu.edu.cn/",
        "university_location",
        "Northwest A&F University (Yangling).",
    ),
    "TCL CORP": (
        "Huizhou",
        "Guangdong",
        "https://www.tcl.com/",
        "official_headquarters_page",
        "TCL Technology.",
    ),
    "INST INF ENG CAS": (
        "Beijing",
        "Beijing",
        "https://english.ie.cas.cn/",
        "university_location",
        "Institute of Information Engineering, CAS.",
    ),
    "UNIV NORTHWESTERN": (
        "Xi'an",
        "Shaanxi",
        "https://www.nwu.edu.cn/",
        "university_location",
        "Northwest University (Xi'an).",
    ),
    "INST CHEMISTRY CAS": (
        "Beijing",
        "Beijing",
        "https://english.ic.cas.cn/",
        "university_location",
        "Institute of Chemistry, CAS.",
    ),
    "GUANGDONG MIDEA REFRIGERATION EQUIPMENT CO LTD": (
        "Foshan",
        "Guangdong",
        "https://www.midea.com/",
        "official_headquarters_page",
        "Midea Group (Guangdong subsidiary).",
    ),
    "UNIV SOUTHWEST": (
        "Chongqing",
        "Chongqing",
        "https://www.swu.edu.cn/",
        "university_location",
        "Southwest University.",
    ),
    "UNIV LIAONING TECHNICAL": (
        "Jinzhou",
        "Liaoning",
        "https://www.lntu.edu.cn/",
        "university_location",
        "Liaoning Technical University.",
    ),
    "UNIV JILIN": (
        "Changchun",
        "Jilin",
        "https://www.jlu.edu.cn/",
        "university_location",
        "Jilin University.",
    ),
    "UNIV HOHAI": (
        "Nanjing",
        "Jiangsu",
        "https://www.hhu.edu.cn/",
        "university_location",
        "Hohai University.",
    ),
    "UNIV SICHUAN": (
        "Chengdu",
        "Sichuan",
        "https://www.scu.edu.cn/",
        "university_location",
        "Sichuan University.",
    ),
    "UNIV JIANGNAN": (
        "Wuxi",
        "Jiangsu",
        "https://www.jiangnan.edu.cn/",
        "university_location",
        "Jiangnan University.",
    ),
    "UNIV JIANGSU": (
        "Nanjing",
        "Jiangsu",
        "https://www.ujs.edu.cn/",
        "university_location",
        "Jiangsu University.",
    ),
    "UNIV TONGJI": (
        "Shanghai",
        "Shanghai",
        "https://www.tongji.edu.cn/",
        "university_location",
        "Tongji University.",
    ),
    "UNIV NORTHWESTERN POLYTECHNICAL": (
        "Xi'an",
        "Shaanxi",
        "https://www.nwpu.edu.cn/",
        "university_location",
        "Northwestern Polytechnical University.",
    ),
    "UNIV ZHEJIANG TECHNOLOGY": (
        "Hangzhou",
        "Zhejiang",
        "https://www.zjut.edu.cn/",
        "university_location",
        "Zhejiang University of Technology.",
    ),
    "CHINA PETROLEUM & CHEMICAL CORP": (
        "Beijing",
        "Beijing",
        "https://www.sinopec.com/",
        "official_headquarters_page",
        "Sinopec Group.",
    ),
    "CHINA PETROLEUM & CHEMICAL CORP SINOPEC": (
        "Beijing",
        "Beijing",
        "https://www.sinopec.com/",
        "official_headquarters_page",
        "Sinopec Group.",
    ),
    "PETROCHINA CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.petrochina.com.cn/",
        "official_headquarters_page",
        "PetroChina.",
    ),
    "CHINA UNICOM": (
        "Beijing",
        "Beijing",
        "https://www.chinaunicom.com.cn/",
        "official_headquarters_page",
        "China Unicom.",
    ),
    "CHINA UNICOM GROUP CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.chinaunicom.com.cn/",
        "official_headquarters_page",
        "China Unicom Group.",
    ),
    "XIAOMI INC": (
        "Beijing",
        "Beijing",
        "https://www.mi.com/",
        "official_headquarters_page",
        "Xiaomi Corporation.",
    ),
    "BEIJING XIAOMI MOBILE SOFTWARE CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.mi.com/",
        "official_headquarters_page",
        "Xiaomi mobile software entity.",
    ),
    "LENOVO BEIJING LTD": (
        "Beijing",
        "Beijing",
        "https://www.lenovo.com/",
        "official_headquarters_page",
        "Lenovo (Beijing).",
    ),
    "MEITUAN": (
        "Beijing",
        "Beijing",
        "https://www.meituan.com/",
        "official_headquarters_page",
        "Meituan.",
    ),
    "BEIJING JINGDONG SHANGKE INFORMATION TECH CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.jd.com/",
        "official_headquarters_page",
        "JD.com.",
    ),
    "NETEASE HANGZHOU NETWORK CO LTD": (
        "Hangzhou",
        "Zhejiang",
        "https://www.netease.com/",
        "official_headquarters_page",
        "NetEase (Hangzhou).",
    ),
    "BANK OF CHINA LTD": (
        "Beijing",
        "Beijing",
        "https://www.boc.cn/",
        "official_headquarters_page",
        "Bank of China.",
    ),
    "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LTD": (
        "Beijing",
        "Beijing",
        "https://www.icbc.com.cn/",
        "official_headquarters_page",
        "ICBC.",
    ),
    "BANK OF COMMUNICATIONS CO LTD": (
        "Shanghai",
        "Shanghai",
        "https://www.bankcomm.com/",
        "official_headquarters_page",
        "Bank of Communications.",
    ),
    "CHINA MINSHENG BANKING CORP LTD": (
        "Beijing",
        "Beijing",
        "https://www.cmbc.com.cn/",
        "official_headquarters_page",
        "China Minsheng Bank.",
    ),
    "CHINA EVERBRIGHT BANK CO LTD": (
        "Beijing",
        "Beijing",
        "https://www.cebbank.com/",
        "official_headquarters_page",
        "China Everbright Bank.",
    ),
    "HUAWEI CLOUD COMPUTING TECHNOLOGIES CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.huaweicloud.com/",
        "official_headquarters_page",
        "Huawei Cloud.",
    ),
    "BYD CO LTD": (
        "Shenzhen",
        "Guangdong",
        "https://www.byd.com/",
        "official_headquarters_page",
        "BYD Company.",
    ),
    "CONTEMPORARY AMPEREX TECHNOLOGY CO LTD": (
        "Ningde",
        "Fujian",
        "https://www.catl.com/",
        "official_headquarters_page",
        "CATL.",
    ),
    "WUXI APPTEC CO LTD": (
        "Wuxi",
        "Jiangsu",
        "https://www.wuxiapptec.com/",
        "official_headquarters_page",
        "WuXi AppTec.",
    ),
    "WILL SEMICONDUCTOR CO LTD SHANGHAI": (
        "Shanghai",
        "Shanghai",
        "https://www.omnivision-group.com/",
        "official_headquarters_page",
        "Will Semiconductor / OmniVision.",
    ),
    "SEMICONDUCTOR MANUFACTURING INTERNATIONAL CORP": (
        "Shanghai",
        "Shanghai",
        "https://www.smics.com/",
        "official_headquarters_page",
        "SMIC (mainland listing).",
    ),
    "HUA HONG SEMICONDUCTOR LTD": (
        "Shanghai",
        "Shanghai",
        "https://www.huahonggrace.com/",
        "official_headquarters_page",
        "Hua Hong Semiconductor.",
    ),
    "YANGTZE MEMORY TECHNOLOGIES CO LTD": (
        "Wuhan",
        "Hubei",
        "https://www.ymtc.com/",
        "official_headquarters_page",
        "YMTC.",
    ),
    "GREE ELECTRIC APPLIANCES INC OF ZHUHAI": (
        "Zhuhai",
        "Guangdong",
        "https://www.gree.com/",
        "official_headquarters_page",
        "Gree Electric Appliances.",
    ),
    "MIDEA GROUP CO LTD": (
        "Foshan",
        "Guangdong",
        "https://www.midea.com/",
        "official_headquarters_page",
        "Midea Group.",
    ),
    "HAIER SMART HOME CO LTD": (
        "Qingdao",
        "Shandong",
        "https://www.haier.com/",
        "official_headquarters_page",
        "Haier Smart Home.",
    ),
    "TSINGHUA UNIV": (
        "Beijing",
        "Beijing",
        "https://www.tsinghua.edu.cn/en/",
        "university_location",
        "Tsinghua University (alias).",
    ),
    "PEKING UNIV": (
        "Beijing",
        "Beijing",
        "https://english.pku.edu.cn/",
        "university_location",
        "Peking University (alias).",
    ),
}

FOREIGN_APPLICANT_MARKERS: tuple[str, ...] = (
    "SAMSUNG",
    "LG CHEMICAL",
    "LG DISPLAY",
    "LG ELECTRONICS",
    "TOYOTA",
    "QUALCOMM",
    "INTEL CORP",
    "MICROSOFT",
    "SONY",
    "FORD GLOBAL",
    "GM GLOBAL",
    "HONDA",
    "CANON",
    "FANUC",
    "BOSCH",
    "PANASONIC",
    "MITSUBISHI",
    "ERICSSON",
    "TOKYO ELECTRON",
    "TAIWAN SEMICONDUCTOR",
    "SEMICONDUCTOR MFG INT",
    "SIEMENS",
    "HYUNDAI",
    "SHARP",
    "APPLIED MATERIALS",
    "GEN ELECTRIC",
    "INFINEON",
    "PHILIPS",
    "TOSHIBA",
    "NOKIA",
    "NVIDIA",
    "APPLE INC",
    "HEWLETT",
    "ORACLE",
    "AMAZON",
    "GOOGLE",
    "KONINKLIJKE",
    "SCHNEIDER",
    "HONEYWELL",
    "DELL",
    "CISCO",
    "IBM",
    "3M ",
    "SEIKO EPSON",
    "EPSON",
    "OMRON",
    "DISCO CORP",
    "MURATA",
    "FUJIFILM",
    "BOEING",
    "SUMITOMO",
    "SK HYNIX",
    "MICRON",
    "NTT DOCOMO",
    "MEDIATEK",
    "SHIMADZU",
    "FUJITSU",
    "DENSO",
    "IND TECH RES INST",
    "NATIONAL DONG HWA",
    "YAMAHA",
    "ROHM",
    "HITACHI",
    "NISSAN",
    "SUBARU",
    "MAZDA",
    "BRIDGESTONE",
    "ASAHI",
    "KAO CORP",
    "KUBOTA",
    "KOMATSU",
    "NITTO DENKO",
    "RENESAS",
    "AU OPTRONICS",
    "LAM RES",
    "UNITED MICROELECTRONICS",
    "DENSO",
    "SHIMADZU",
    "FUJITSU",
    "MURATA",
    "OMRON",
    "DISCO CORP",
    "SEIKO EPSON",
    "EPSON",
    "BOEING",
)


def is_foreign_applicant(name: str) -> bool:
    upper = name.upper()
    return any(marker in upper for marker in FOREIGN_APPLICANT_MARKERS)


def geography_from_institution_registry(applicant_name: str) -> dict[str, str] | None:
    """Contract geography row from curated HQ registry (first applicant only)."""
    from diffusion_state.china_city_gazetteer import first_applicant_name

    first = first_applicant_name(applicant_name)
    if not first or is_foreign_applicant(first):
        return None
    loc = CURATED_LOCATIONS.get(first)
    if not loc:
        return None
    city, province, source_url, conf, notes = loc
    return {
        "applicant_city": city,
        "applicant_province": province,
        "applicant_address": f"{city}, {province}, CN (curated institution registry)",
        "geo_source": source_url,
        "geo_match_confidence": conf,
        "geo_notes": notes,
    }
